/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OmRouteImport } from './routes/om'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TakoffertRouteImport } from './routes/takoffert'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as LeadKontaktadRouteImport } from './routes/lead/kontaktad'
import { Route as OffertSlugRouteImport } from './routes/offert.$slug'
import { Route as TestTakoffertRouteImport } from './routes/test.takoffert'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCustomerIdRouteImport } from './routes/_authenticated/admin/$customerId'
import { Route as AuthenticatedAdminAgentsRouteImport } from './routes/_authenticated/admin/agents'
import { Route as AuthenticatedAdminAiAssistentRouteImport } from './routes/_authenticated/admin/ai-assistent'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin/crm'
import { Route as AuthenticatedAdminGrowthRouteImport } from './routes/_authenticated/admin/growth'
import { Route as AuthenticatedAdminKonversationerRouteImport } from './routes/_authenticated/admin/konversationer'
import { Route as AuthenticatedAdminProfilerRouteImport } from './routes/_authenticated/admin/profiler'
import { Route as TestOffertSlugRouteImport } from './routes/test.offert.$slug'
import { Route as ApiPublicAgentsAutonomousTickRouteImport } from './routes/api/public/agents/autonomous-tick'
import { Route as ApiPublicAgentsDispatchTestRouteImport } from './routes/api/public/agents/dispatch-test'
import { Route as ApiPublicAgentsImprovementReviewTestRouteImport } from './routes/api/public/agents/improvement-review-test'
import { Route as ApiPublicAgentsProcessShadowBatchTestRouteImport } from './routes/api/public/agents/process-shadow-batch-test'
import { Route as ApiPublicAgentsProcessTestRouteImport } from './routes/api/public/agents/process-test'
import { Route as ApiPublicAgentsShadowReviewTestRouteImport } from './routes/api/public/agents/shadow-review-test'
import { Route as ApiPublicGrowthAnalyzeLeadRouteImport } from './routes/api/public/growth/analyze-lead'
import { Route as ApiPublicGrowthAssignVariantRouteImport } from './routes/api/public/growth/assign-variant'
import { Route as ApiPublicGrowthClaimLeadReminderRouteImport } from './routes/api/public/growth/claim-lead-reminder'
import { Route as ApiPublicGrowthClaimNurtureReviewRouteImport } from './routes/api/public/growth/claim-nurture-review'
import { Route as ApiPublicGrowthCompleteLeadReminderRouteImport } from './routes/api/public/growth/complete-lead-reminder'
import { Route as ApiPublicGrowthCompleteNurtureReviewRouteImport } from './routes/api/public/growth/complete-nurture-review'
import { Route as ApiPublicGrowthCustomerConfigRouteImport } from './routes/api/public/growth/customer-config'
import { Route as ApiPublicGrowthDeliveryRecoveryRouteImport } from './routes/api/public/growth/delivery-recovery'
import { Route as ApiPublicGrowthDueLeadRemindersRouteImport } from './routes/api/public/growth/due-lead-reminders'
import { Route as ApiPublicGrowthDueNurtureReviewsRouteImport } from './routes/api/public/growth/due-nurture-reviews'
import { Route as ApiPublicGrowthFailLeadReminderRouteImport } from './routes/api/public/growth/fail-lead-reminder'
import { Route as ApiPublicGrowthFailNurtureReviewRouteImport } from './routes/api/public/growth/fail-nurture-review'
import { Route as ApiPublicGrowthGrowthRecommendationRouteImport } from './routes/api/public/growth/growth-recommendation'
import { Route as ApiPublicGrowthPlanNurtureTestRouteImport } from './routes/api/public/growth/plan-nurture-test'
import { Route as ApiPublicGrowthRegisterNurtureReplyTestRouteImport } from './routes/api/public/growth/register-nurture-reply-test'
import { Route as ApiPublicGrowthRegisterOutcomeRouteImport } from './routes/api/public/growth/register-outcome'
import { Route as ApiPublicGrowthRegisterReviewedNurtureReplyRouteImport } from './routes/api/public/growth/register-reviewed-nurture-reply'
import { Route as ApiPublicGrowthReviewReconciliationRouteImport } from './routes/api/public/growth/review-reconciliation'
import { Route as ApiPublicGrowthRouteLeadRouteImport } from './routes/api/public/growth/route-lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TakoffertRoute = TakoffertRouteImport.update({
  id: '/takoffert',
  path: '/takoffert',
  getParentRoute: () => rootRouteImport,
} as any)
const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const LeadKontaktadRoute = LeadKontaktadRouteImport.update({
  id: '/lead/kontaktad',
  path: '/lead/kontaktad',
  getParentRoute: () => rootRouteImport,
} as any)
const OffertSlugRoute = OffertSlugRouteImport.update({
  id: '/offert/$slug',
  path: '/offert/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTakoffertRoute = TestTakoffertRouteImport.update({
  id: '/test/takoffert',
  path: '/test/takoffert',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCustomerIdRoute =
  AuthenticatedAdminCustomerIdRouteImport.update({
    id: '/admin/$customerId',
    path: '/admin/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAgentsRoute =
  AuthenticatedAdminAgentsRouteImport.update({
    id: '/admin/agents',
    path: '/admin/agents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAiAssistentRoute =
  AuthenticatedAdminAiAssistentRouteImport.update({
    id: '/admin/ai-assistent',
    path: '/admin/ai-assistent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGrowthRoute =
  AuthenticatedAdminGrowthRouteImport.update({
    id: '/admin/growth',
    path: '/admin/growth',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKonversationerRoute =
  AuthenticatedAdminKonversationerRouteImport.update({
    id: '/admin/konversationer',
    path: '/admin/konversationer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProfilerRoute =
  AuthenticatedAdminProfilerRouteImport.update({
    id: '/admin/profiler',
    path: '/admin/profiler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const TestOffertSlugRoute = TestOffertSlugRouteImport.update({
  id: '/test/offert/$slug',
  path: '/test/offert/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentsAutonomousTickRoute =
  ApiPublicAgentsAutonomousTickRouteImport.update({
    id: '/api/public/agents/autonomous-tick',
    path: '/api/public/agents/autonomous-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentsDispatchTestRoute =
  ApiPublicAgentsDispatchTestRouteImport.update({
    id: '/api/public/agents/dispatch-test',
    path: '/api/public/agents/dispatch-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentsImprovementReviewTestRoute =
  ApiPublicAgentsImprovementReviewTestRouteImport.update({
    id: '/api/public/agents/improvement-review-test',
    path: '/api/public/agents/improvement-review-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentsProcessShadowBatchTestRoute =
  ApiPublicAgentsProcessShadowBatchTestRouteImport.update({
    id: '/api/public/agents/process-shadow-batch-test',
    path: '/api/public/agents/process-shadow-batch-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentsProcessTestRoute =
  ApiPublicAgentsProcessTestRouteImport.update({
    id: '/api/public/agents/process-test',
    path: '/api/public/agents/process-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgentsShadowReviewTestRoute =
  ApiPublicAgentsShadowReviewTestRouteImport.update({
    id: '/api/public/agents/shadow-review-test',
    path: '/api/public/agents/shadow-review-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthAnalyzeLeadRoute =
  ApiPublicGrowthAnalyzeLeadRouteImport.update({
    id: '/api/public/growth/analyze-lead',
    path: '/api/public/growth/analyze-lead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthAssignVariantRoute =
  ApiPublicGrowthAssignVariantRouteImport.update({
    id: '/api/public/growth/assign-variant',
    path: '/api/public/growth/assign-variant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthClaimLeadReminderRoute =
  ApiPublicGrowthClaimLeadReminderRouteImport.update({
    id: '/api/public/growth/claim-lead-reminder',
    path: '/api/public/growth/claim-lead-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthClaimNurtureReviewRoute =
  ApiPublicGrowthClaimNurtureReviewRouteImport.update({
    id: '/api/public/growth/claim-nurture-review',
    path: '/api/public/growth/claim-nurture-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthCompleteLeadReminderRoute =
  ApiPublicGrowthCompleteLeadReminderRouteImport.update({
    id: '/api/public/growth/complete-lead-reminder',
    path: '/api/public/growth/complete-lead-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthCompleteNurtureReviewRoute =
  ApiPublicGrowthCompleteNurtureReviewRouteImport.update({
    id: '/api/public/growth/complete-nurture-review',
    path: '/api/public/growth/complete-nurture-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthCustomerConfigRoute =
  ApiPublicGrowthCustomerConfigRouteImport.update({
    id: '/api/public/growth/customer-config',
    path: '/api/public/growth/customer-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthDeliveryRecoveryRoute =
  ApiPublicGrowthDeliveryRecoveryRouteImport.update({
    id: '/api/public/growth/delivery-recovery',
    path: '/api/public/growth/delivery-recovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthDueLeadRemindersRoute =
  ApiPublicGrowthDueLeadRemindersRouteImport.update({
    id: '/api/public/growth/due-lead-reminders',
    path: '/api/public/growth/due-lead-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthDueNurtureReviewsRoute =
  ApiPublicGrowthDueNurtureReviewsRouteImport.update({
    id: '/api/public/growth/due-nurture-reviews',
    path: '/api/public/growth/due-nurture-reviews',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthFailLeadReminderRoute =
  ApiPublicGrowthFailLeadReminderRouteImport.update({
    id: '/api/public/growth/fail-lead-reminder',
    path: '/api/public/growth/fail-lead-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthFailNurtureReviewRoute =
  ApiPublicGrowthFailNurtureReviewRouteImport.update({
    id: '/api/public/growth/fail-nurture-review',
    path: '/api/public/growth/fail-nurture-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthGrowthRecommendationRoute =
  ApiPublicGrowthGrowthRecommendationRouteImport.update({
    id: '/api/public/growth/growth-recommendation',
    path: '/api/public/growth/growth-recommendation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthPlanNurtureTestRoute =
  ApiPublicGrowthPlanNurtureTestRouteImport.update({
    id: '/api/public/growth/plan-nurture-test',
    path: '/api/public/growth/plan-nurture-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthRegisterNurtureReplyTestRoute =
  ApiPublicGrowthRegisterNurtureReplyTestRouteImport.update({
    id: '/api/public/growth/register-nurture-reply-test',
    path: '/api/public/growth/register-nurture-reply-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthRegisterOutcomeRoute =
  ApiPublicGrowthRegisterOutcomeRouteImport.update({
    id: '/api/public/growth/register-outcome',
    path: '/api/public/growth/register-outcome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthRegisterReviewedNurtureReplyRoute =
  ApiPublicGrowthRegisterReviewedNurtureReplyRouteImport.update({
    id: '/api/public/growth/register-reviewed-nurture-reply',
    path: '/api/public/growth/register-reviewed-nurture-reply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthReviewReconciliationRoute =
  ApiPublicGrowthReviewReconciliationRouteImport.update({
    id: '/api/public/growth/review-reconciliation',
    path: '/api/public/growth/review-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthRouteLeadRoute =
  ApiPublicGrowthRouteLeadRouteImport.update({
    id: '/api/public/growth/route-lead',
    path: '/api/public/growth/route-lead',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/om': typeof OmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takoffert': typeof TakoffertRoute
  '/villkor': typeof VillkorRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lead/kontaktad': typeof LeadKontaktadRoute
  '/offert/$slug': typeof OffertSlugRoute
  '/test/takoffert': typeof TestTakoffertRoute
  '/admin/$customerId': typeof AuthenticatedAdminCustomerIdRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/ai-assistent': typeof AuthenticatedAdminAiAssistentRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/growth': typeof AuthenticatedAdminGrowthRoute
  '/admin/konversationer': typeof AuthenticatedAdminKonversationerRoute
  '/admin/profiler': typeof AuthenticatedAdminProfilerRoute
  '/test/offert/$slug': typeof TestOffertSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/agents/autonomous-tick': typeof ApiPublicAgentsAutonomousTickRoute
  '/api/public/agents/dispatch-test': typeof ApiPublicAgentsDispatchTestRoute
  '/api/public/agents/improvement-review-test': typeof ApiPublicAgentsImprovementReviewTestRoute
  '/api/public/agents/process-shadow-batch-test': typeof ApiPublicAgentsProcessShadowBatchTestRoute
  '/api/public/agents/process-test': typeof ApiPublicAgentsProcessTestRoute
  '/api/public/agents/shadow-review-test': typeof ApiPublicAgentsShadowReviewTestRoute
  '/api/public/growth/analyze-lead': typeof ApiPublicGrowthAnalyzeLeadRoute
  '/api/public/growth/assign-variant': typeof ApiPublicGrowthAssignVariantRoute
  '/api/public/growth/claim-lead-reminder': typeof ApiPublicGrowthClaimLeadReminderRoute
  '/api/public/growth/claim-nurture-review': typeof ApiPublicGrowthClaimNurtureReviewRoute
  '/api/public/growth/complete-lead-reminder': typeof ApiPublicGrowthCompleteLeadReminderRoute
  '/api/public/growth/complete-nurture-review': typeof ApiPublicGrowthCompleteNurtureReviewRoute
  '/api/public/growth/customer-config': typeof ApiPublicGrowthCustomerConfigRoute
  '/api/public/growth/delivery-recovery': typeof ApiPublicGrowthDeliveryRecoveryRoute
  '/api/public/growth/due-lead-reminders': typeof ApiPublicGrowthDueLeadRemindersRoute
  '/api/public/growth/due-nurture-reviews': typeof ApiPublicGrowthDueNurtureReviewsRoute
  '/api/public/growth/fail-lead-reminder': typeof ApiPublicGrowthFailLeadReminderRoute
  '/api/public/growth/fail-nurture-review': typeof ApiPublicGrowthFailNurtureReviewRoute
  '/api/public/growth/growth-recommendation': typeof ApiPublicGrowthGrowthRecommendationRoute
  '/api/public/growth/plan-nurture-test': typeof ApiPublicGrowthPlanNurtureTestRoute
  '/api/public/growth/register-nurture-reply-test': typeof ApiPublicGrowthRegisterNurtureReplyTestRoute
  '/api/public/growth/register-outcome': typeof ApiPublicGrowthRegisterOutcomeRoute
  '/api/public/growth/register-reviewed-nurture-reply': typeof ApiPublicGrowthRegisterReviewedNurtureReplyRoute
  '/api/public/growth/review-reconciliation': typeof ApiPublicGrowthReviewReconciliationRoute
  '/api/public/growth/route-lead': typeof ApiPublicGrowthRouteLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/om': typeof OmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takoffert': typeof TakoffertRoute
  '/villkor': typeof VillkorRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lead/kontaktad': typeof LeadKontaktadRoute
  '/offert/$slug': typeof OffertSlugRoute
  '/test/takoffert': typeof TestTakoffertRoute
  '/admin/$customerId': typeof AuthenticatedAdminCustomerIdRoute
  '/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/admin/ai-assistent': typeof AuthenticatedAdminAiAssistentRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/growth': typeof AuthenticatedAdminGrowthRoute
  '/admin/konversationer': typeof AuthenticatedAdminKonversationerRoute
  '/admin/profiler': typeof AuthenticatedAdminProfilerRoute
  '/test/offert/$slug': typeof TestOffertSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/agents/autonomous-tick': typeof ApiPublicAgentsAutonomousTickRoute
  '/api/public/agents/dispatch-test': typeof ApiPublicAgentsDispatchTestRoute
  '/api/public/agents/improvement-review-test': typeof ApiPublicAgentsImprovementReviewTestRoute
  '/api/public/agents/process-shadow-batch-test': typeof ApiPublicAgentsProcessShadowBatchTestRoute
  '/api/public/agents/process-test': typeof ApiPublicAgentsProcessTestRoute
  '/api/public/agents/shadow-review-test': typeof ApiPublicAgentsShadowReviewTestRoute
  '/api/public/growth/analyze-lead': typeof ApiPublicGrowthAnalyzeLeadRoute
  '/api/public/growth/assign-variant': typeof ApiPublicGrowthAssignVariantRoute
  '/api/public/growth/claim-lead-reminder': typeof ApiPublicGrowthClaimLeadReminderRoute
  '/api/public/growth/claim-nurture-review': typeof ApiPublicGrowthClaimNurtureReviewRoute
  '/api/public/growth/complete-lead-reminder': typeof ApiPublicGrowthCompleteLeadReminderRoute
  '/api/public/growth/complete-nurture-review': typeof ApiPublicGrowthCompleteNurtureReviewRoute
  '/api/public/growth/customer-config': typeof ApiPublicGrowthCustomerConfigRoute
  '/api/public/growth/delivery-recovery': typeof ApiPublicGrowthDeliveryRecoveryRoute
  '/api/public/growth/due-lead-reminders': typeof ApiPublicGrowthDueLeadRemindersRoute
  '/api/public/growth/due-nurture-reviews': typeof ApiPublicGrowthDueNurtureReviewsRoute
  '/api/public/growth/fail-lead-reminder': typeof ApiPublicGrowthFailLeadReminderRoute
  '/api/public/growth/fail-nurture-review': typeof ApiPublicGrowthFailNurtureReviewRoute
  '/api/public/growth/growth-recommendation': typeof ApiPublicGrowthGrowthRecommendationRoute
  '/api/public/growth/plan-nurture-test': typeof ApiPublicGrowthPlanNurtureTestRoute
  '/api/public/growth/register-nurture-reply-test': typeof ApiPublicGrowthRegisterNurtureReplyTestRoute
  '/api/public/growth/register-outcome': typeof ApiPublicGrowthRegisterOutcomeRoute
  '/api/public/growth/register-reviewed-nurture-reply': typeof ApiPublicGrowthRegisterReviewedNurtureReplyRoute
  '/api/public/growth/review-reconciliation': typeof ApiPublicGrowthReviewReconciliationRoute
  '/api/public/growth/route-lead': typeof ApiPublicGrowthRouteLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/mcp': typeof McpRoute
  '/om': typeof OmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takoffert': typeof TakoffertRoute
  '/villkor': typeof VillkorRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/lead/kontaktad': typeof LeadKontaktadRoute
  '/offert/$slug': typeof OffertSlugRoute
  '/test/takoffert': typeof TestTakoffertRoute
  '/_authenticated/admin/$customerId': typeof AuthenticatedAdminCustomerIdRoute
  '/_authenticated/admin/agents': typeof AuthenticatedAdminAgentsRoute
  '/_authenticated/admin/ai-assistent': typeof AuthenticatedAdminAiAssistentRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/growth': typeof AuthenticatedAdminGrowthRoute
  '/_authenticated/admin/konversationer': typeof AuthenticatedAdminKonversationerRoute
  '/_authenticated/admin/profiler': typeof AuthenticatedAdminProfilerRoute
  '/test/offert/$slug': typeof TestOffertSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/agents/autonomous-tick': typeof ApiPublicAgentsAutonomousTickRoute
  '/api/public/agents/dispatch-test': typeof ApiPublicAgentsDispatchTestRoute
  '/api/public/agents/improvement-review-test': typeof ApiPublicAgentsImprovementReviewTestRoute
  '/api/public/agents/process-shadow-batch-test': typeof ApiPublicAgentsProcessShadowBatchTestRoute
  '/api/public/agents/process-test': typeof ApiPublicAgentsProcessTestRoute
  '/api/public/agents/shadow-review-test': typeof ApiPublicAgentsShadowReviewTestRoute
  '/api/public/growth/analyze-lead': typeof ApiPublicGrowthAnalyzeLeadRoute
  '/api/public/growth/assign-variant': typeof ApiPublicGrowthAssignVariantRoute
  '/api/public/growth/claim-lead-reminder': typeof ApiPublicGrowthClaimLeadReminderRoute
  '/api/public/growth/claim-nurture-review': typeof ApiPublicGrowthClaimNurtureReviewRoute
  '/api/public/growth/complete-lead-reminder': typeof ApiPublicGrowthCompleteLeadReminderRoute
  '/api/public/growth/complete-nurture-review': typeof ApiPublicGrowthCompleteNurtureReviewRoute
  '/api/public/growth/customer-config': typeof ApiPublicGrowthCustomerConfigRoute
  '/api/public/growth/delivery-recovery': typeof ApiPublicGrowthDeliveryRecoveryRoute
  '/api/public/growth/due-lead-reminders': typeof ApiPublicGrowthDueLeadRemindersRoute
  '/api/public/growth/due-nurture-reviews': typeof ApiPublicGrowthDueNurtureReviewsRoute
  '/api/public/growth/fail-lead-reminder': typeof ApiPublicGrowthFailLeadReminderRoute
  '/api/public/growth/fail-nurture-review': typeof ApiPublicGrowthFailNurtureReviewRoute
  '/api/public/growth/growth-recommendation': typeof ApiPublicGrowthGrowthRecommendationRoute
  '/api/public/growth/plan-nurture-test': typeof ApiPublicGrowthPlanNurtureTestRoute
  '/api/public/growth/register-nurture-reply-test': typeof ApiPublicGrowthRegisterNurtureReplyTestRoute
  '/api/public/growth/register-outcome': typeof ApiPublicGrowthRegisterOutcomeRoute
  '/api/public/growth/register-reviewed-nurture-reply': typeof ApiPublicGrowthRegisterReviewedNurtureReplyRoute
  '/api/public/growth/review-reconciliation': typeof ApiPublicGrowthReviewReconciliationRoute
  '/api/public/growth/route-lead': typeof ApiPublicGrowthRouteLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/faq'
    | '/integritetspolicy'
    | '/kontakt'
    | '/mcp'
    | '/om'
    | '/sitemap.xml'
    | '/takoffert'
    | '/villkor'
    | '/.well-known/oauth-protected-resource'
    | '/lead/kontaktad'
    | '/offert/$slug'
    | '/test/takoffert'
    | '/admin/$customerId'
    | '/admin/agents'
    | '/admin/ai-assistent'
    | '/admin/crm'
    | '/admin/growth'
    | '/admin/konversationer'
    | '/admin/profiler'
    | '/test/offert/$slug'
    | '/admin/'
    | '/api/public/agents/autonomous-tick'
    | '/api/public/agents/dispatch-test'
    | '/api/public/agents/improvement-review-test'
    | '/api/public/agents/process-shadow-batch-test'
    | '/api/public/agents/process-test'
    | '/api/public/agents/shadow-review-test'
    | '/api/public/growth/analyze-lead'
    | '/api/public/growth/assign-variant'
    | '/api/public/growth/claim-lead-reminder'
    | '/api/public/growth/claim-nurture-review'
    | '/api/public/growth/complete-lead-reminder'
    | '/api/public/growth/complete-nurture-review'
    | '/api/public/growth/customer-config'
    | '/api/public/growth/delivery-recovery'
    | '/api/public/growth/due-lead-reminders'
    | '/api/public/growth/due-nurture-reviews'
    | '/api/public/growth/fail-lead-reminder'
    | '/api/public/growth/fail-nurture-review'
    | '/api/public/growth/growth-recommendation'
    | '/api/public/growth/plan-nurture-test'
    | '/api/public/growth/register-nurture-reply-test'
    | '/api/public/growth/register-outcome'
    | '/api/public/growth/register-reviewed-nurture-reply'
    | '/api/public/growth/review-reconciliation'
    | '/api/public/growth/route-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/faq'
    | '/integritetspolicy'
    | '/kontakt'
    | '/mcp'
    | '/om'
    | '/sitemap.xml'
    | '/takoffert'
    | '/villkor'
    | '/.well-known/oauth-protected-resource'
    | '/lead/kontaktad'
    | '/offert/$slug'
    | '/test/takoffert'
    | '/admin/$customerId'
    | '/admin/agents'
    | '/admin/ai-assistent'
    | '/admin/crm'
    | '/admin/growth'
    | '/admin/konversationer'
    | '/admin/profiler'
    | '/test/offert/$slug'
    | '/admin'
    | '/api/public/agents/autonomous-tick'
    | '/api/public/agents/dispatch-test'
    | '/api/public/agents/improvement-review-test'
    | '/api/public/agents/process-shadow-batch-test'
    | '/api/public/agents/process-test'
    | '/api/public/agents/shadow-review-test'
    | '/api/public/growth/analyze-lead'
    | '/api/public/growth/assign-variant'
    | '/api/public/growth/claim-lead-reminder'
    | '/api/public/growth/claim-nurture-review'
    | '/api/public/growth/complete-lead-reminder'
    | '/api/public/growth/complete-nurture-review'
    | '/api/public/growth/customer-config'
    | '/api/public/growth/delivery-recovery'
    | '/api/public/growth/due-lead-reminders'
    | '/api/public/growth/due-nurture-reviews'
    | '/api/public/growth/fail-lead-reminder'
    | '/api/public/growth/fail-nurture-review'
    | '/api/public/growth/growth-recommendation'
    | '/api/public/growth/plan-nurture-test'
    | '/api/public/growth/register-nurture-reply-test'
    | '/api/public/growth/register-outcome'
    | '/api/public/growth/register-reviewed-nurture-reply'
    | '/api/public/growth/review-reconciliation'
    | '/api/public/growth/route-lead'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/faq'
    | '/integritetspolicy'
    | '/kontakt'
    | '/mcp'
    | '/om'
    | '/sitemap.xml'
    | '/takoffert'
    | '/villkor'
    | '/.well-known/oauth-protected-resource'
    | '/lead/kontaktad'
    | '/offert/$slug'
    | '/test/takoffert'
    | '/_authenticated/admin/$customerId'
    | '/_authenticated/admin/agents'
    | '/_authenticated/admin/ai-assistent'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/growth'
    | '/_authenticated/admin/konversationer'
    | '/_authenticated/admin/profiler'
    | '/test/offert/$slug'
    | '/_authenticated/admin/'
    | '/api/public/agents/autonomous-tick'
    | '/api/public/agents/dispatch-test'
    | '/api/public/agents/improvement-review-test'
    | '/api/public/agents/process-shadow-batch-test'
    | '/api/public/agents/process-test'
    | '/api/public/agents/shadow-review-test'
    | '/api/public/growth/analyze-lead'
    | '/api/public/growth/assign-variant'
    | '/api/public/growth/claim-lead-reminder'
    | '/api/public/growth/claim-nurture-review'
    | '/api/public/growth/complete-lead-reminder'
    | '/api/public/growth/complete-nurture-review'
    | '/api/public/growth/customer-config'
    | '/api/public/growth/delivery-recovery'
    | '/api/public/growth/due-lead-reminders'
    | '/api/public/growth/due-nurture-reviews'
    | '/api/public/growth/fail-lead-reminder'
    | '/api/public/growth/fail-nurture-review'
    | '/api/public/growth/growth-recommendation'
    | '/api/public/growth/plan-nurture-test'
    | '/api/public/growth/register-nurture-reply-test'
    | '/api/public/growth/register-outcome'
    | '/api/public/growth/register-reviewed-nurture-reply'
    | '/api/public/growth/review-reconciliation'
    | '/api/public/growth/route-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KontaktRoute: typeof KontaktRoute
  McpRoute: typeof McpRoute
  OmRoute: typeof OmRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TakoffertRoute: typeof TakoffertRoute
  VillkorRoute: typeof VillkorRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  LeadKontaktadRoute: typeof LeadKontaktadRoute
  OffertSlugRoute: typeof OffertSlugRoute
  TestTakoffertRoute: typeof TestTakoffertRoute
  TestOffertSlugRoute: typeof TestOffertSlugRoute
  ApiPublicAgentsAutonomousTickRoute: typeof ApiPublicAgentsAutonomousTickRoute
  ApiPublicAgentsDispatchTestRoute: typeof ApiPublicAgentsDispatchTestRoute
  ApiPublicAgentsImprovementReviewTestRoute: typeof ApiPublicAgentsImprovementReviewTestRoute
  ApiPublicAgentsProcessShadowBatchTestRoute: typeof ApiPublicAgentsProcessShadowBatchTestRoute
  ApiPublicAgentsProcessTestRoute: typeof ApiPublicAgentsProcessTestRoute
  ApiPublicAgentsShadowReviewTestRoute: typeof ApiPublicAgentsShadowReviewTestRoute
  ApiPublicGrowthAnalyzeLeadRoute: typeof ApiPublicGrowthAnalyzeLeadRoute
  ApiPublicGrowthAssignVariantRoute: typeof ApiPublicGrowthAssignVariantRoute
  ApiPublicGrowthClaimLeadReminderRoute: typeof ApiPublicGrowthClaimLeadReminderRoute
  ApiPublicGrowthClaimNurtureReviewRoute: typeof ApiPublicGrowthClaimNurtureReviewRoute
  ApiPublicGrowthCompleteLeadReminderRoute: typeof ApiPublicGrowthCompleteLeadReminderRoute
  ApiPublicGrowthCompleteNurtureReviewRoute: typeof ApiPublicGrowthCompleteNurtureReviewRoute
  ApiPublicGrowthCustomerConfigRoute: typeof ApiPublicGrowthCustomerConfigRoute
  ApiPublicGrowthDeliveryRecoveryRoute: typeof ApiPublicGrowthDeliveryRecoveryRoute
  ApiPublicGrowthDueLeadRemindersRoute: typeof ApiPublicGrowthDueLeadRemindersRoute
  ApiPublicGrowthDueNurtureReviewsRoute: typeof ApiPublicGrowthDueNurtureReviewsRoute
  ApiPublicGrowthFailLeadReminderRoute: typeof ApiPublicGrowthFailLeadReminderRoute
  ApiPublicGrowthFailNurtureReviewRoute: typeof ApiPublicGrowthFailNurtureReviewRoute
  ApiPublicGrowthGrowthRecommendationRoute: typeof ApiPublicGrowthGrowthRecommendationRoute
  ApiPublicGrowthPlanNurtureTestRoute: typeof ApiPublicGrowthPlanNurtureTestRoute
  ApiPublicGrowthRegisterNurtureReplyTestRoute: typeof ApiPublicGrowthRegisterNurtureReplyTestRoute
  ApiPublicGrowthRegisterOutcomeRoute: typeof ApiPublicGrowthRegisterOutcomeRoute
  ApiPublicGrowthRegisterReviewedNurtureReplyRoute: typeof ApiPublicGrowthRegisterReviewedNurtureReplyRoute
  ApiPublicGrowthReviewReconciliationRoute: typeof ApiPublicGrowthReviewReconciliationRoute
  ApiPublicGrowthRouteLeadRoute: typeof ApiPublicGrowthRouteLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takoffert': {
      id: '/takoffert'
      path: '/takoffert'
      fullPath: '/takoffert'
      preLoaderRoute: typeof TakoffertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead/kontaktad': {
      id: '/lead/kontaktad'
      path: '/lead/kontaktad'
      fullPath: '/lead/kontaktad'
      preLoaderRoute: typeof LeadKontaktadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offert/$slug': {
      id: '/offert/$slug'
      path: '/offert/$slug'
      fullPath: '/offert/$slug'
      preLoaderRoute: typeof OffertSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/takoffert': {
      id: '/test/takoffert'
      path: '/test/takoffert'
      fullPath: '/test/takoffert'
      preLoaderRoute: typeof TestTakoffertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$customerId': {
      id: '/_authenticated/admin/$customerId'
      path: '/admin/$customerId'
      fullPath: '/admin/$customerId'
      preLoaderRoute: typeof AuthenticatedAdminCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/agents': {
      id: '/_authenticated/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AuthenticatedAdminAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ai-assistent': {
      id: '/_authenticated/admin/ai-assistent'
      path: '/admin/ai-assistent'
      fullPath: '/admin/ai-assistent'
      preLoaderRoute: typeof AuthenticatedAdminAiAssistentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/growth': {
      id: '/_authenticated/admin/growth'
      path: '/admin/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AuthenticatedAdminGrowthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/konversationer': {
      id: '/_authenticated/admin/konversationer'
      path: '/admin/konversationer'
      fullPath: '/admin/konversationer'
      preLoaderRoute: typeof AuthenticatedAdminKonversationerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/profiler': {
      id: '/_authenticated/admin/profiler'
      path: '/admin/profiler'
      fullPath: '/admin/profiler'
      preLoaderRoute: typeof AuthenticatedAdminProfilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/test/offert/$slug': {
      id: '/test/offert/$slug'
      path: '/test/offert/$slug'
      fullPath: '/test/offert/$slug'
      preLoaderRoute: typeof TestOffertSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/autonomous-tick': {
      id: '/api/public/agents/autonomous-tick'
      path: '/api/public/agents/autonomous-tick'
      fullPath: '/api/public/agents/autonomous-tick'
      preLoaderRoute: typeof ApiPublicAgentsAutonomousTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/dispatch-test': {
      id: '/api/public/agents/dispatch-test'
      path: '/api/public/agents/dispatch-test'
      fullPath: '/api/public/agents/dispatch-test'
      preLoaderRoute: typeof ApiPublicAgentsDispatchTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/improvement-review-test': {
      id: '/api/public/agents/improvement-review-test'
      path: '/api/public/agents/improvement-review-test'
      fullPath: '/api/public/agents/improvement-review-test'
      preLoaderRoute: typeof ApiPublicAgentsImprovementReviewTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/process-shadow-batch-test': {
      id: '/api/public/agents/process-shadow-batch-test'
      path: '/api/public/agents/process-shadow-batch-test'
      fullPath: '/api/public/agents/process-shadow-batch-test'
      preLoaderRoute: typeof ApiPublicAgentsProcessShadowBatchTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/process-test': {
      id: '/api/public/agents/process-test'
      path: '/api/public/agents/process-test'
      fullPath: '/api/public/agents/process-test'
      preLoaderRoute: typeof ApiPublicAgentsProcessTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agents/shadow-review-test': {
      id: '/api/public/agents/shadow-review-test'
      path: '/api/public/agents/shadow-review-test'
      fullPath: '/api/public/agents/shadow-review-test'
      preLoaderRoute: typeof ApiPublicAgentsShadowReviewTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/analyze-lead': {
      id: '/api/public/growth/analyze-lead'
      path: '/api/public/growth/analyze-lead'
      fullPath: '/api/public/growth/analyze-lead'
      preLoaderRoute: typeof ApiPublicGrowthAnalyzeLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/assign-variant': {
      id: '/api/public/growth/assign-variant'
      path: '/api/public/growth/assign-variant'
      fullPath: '/api/public/growth/assign-variant'
      preLoaderRoute: typeof ApiPublicGrowthAssignVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/claim-lead-reminder': {
      id: '/api/public/growth/claim-lead-reminder'
      path: '/api/public/growth/claim-lead-reminder'
      fullPath: '/api/public/growth/claim-lead-reminder'
      preLoaderRoute: typeof ApiPublicGrowthClaimLeadReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/claim-nurture-review': {
      id: '/api/public/growth/claim-nurture-review'
      path: '/api/public/growth/claim-nurture-review'
      fullPath: '/api/public/growth/claim-nurture-review'
      preLoaderRoute: typeof ApiPublicGrowthClaimNurtureReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/complete-lead-reminder': {
      id: '/api/public/growth/complete-lead-reminder'
      path: '/api/public/growth/complete-lead-reminder'
      fullPath: '/api/public/growth/complete-lead-reminder'
      preLoaderRoute: typeof ApiPublicGrowthCompleteLeadReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/complete-nurture-review': {
      id: '/api/public/growth/complete-nurture-review'
      path: '/api/public/growth/complete-nurture-review'
      fullPath: '/api/public/growth/complete-nurture-review'
      preLoaderRoute: typeof ApiPublicGrowthCompleteNurtureReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/customer-config': {
      id: '/api/public/growth/customer-config'
      path: '/api/public/growth/customer-config'
      fullPath: '/api/public/growth/customer-config'
      preLoaderRoute: typeof ApiPublicGrowthCustomerConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/delivery-recovery': {
      id: '/api/public/growth/delivery-recovery'
      path: '/api/public/growth/delivery-recovery'
      fullPath: '/api/public/growth/delivery-recovery'
      preLoaderRoute: typeof ApiPublicGrowthDeliveryRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/due-lead-reminders': {
      id: '/api/public/growth/due-lead-reminders'
      path: '/api/public/growth/due-lead-reminders'
      fullPath: '/api/public/growth/due-lead-reminders'
      preLoaderRoute: typeof ApiPublicGrowthDueLeadRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/due-nurture-reviews': {
      id: '/api/public/growth/due-nurture-reviews'
      path: '/api/public/growth/due-nurture-reviews'
      fullPath: '/api/public/growth/due-nurture-reviews'
      preLoaderRoute: typeof ApiPublicGrowthDueNurtureReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/fail-lead-reminder': {
      id: '/api/public/growth/fail-lead-reminder'
      path: '/api/public/growth/fail-lead-reminder'
      fullPath: '/api/public/growth/fail-lead-reminder'
      preLoaderRoute: typeof ApiPublicGrowthFailLeadReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/fail-nurture-review': {
      id: '/api/public/growth/fail-nurture-review'
      path: '/api/public/growth/fail-nurture-review'
      fullPath: '/api/public/growth/fail-nurture-review'
      preLoaderRoute: typeof ApiPublicGrowthFailNurtureReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/growth-recommendation': {
      id: '/api/public/growth/growth-recommendation'
      path: '/api/public/growth/growth-recommendation'
      fullPath: '/api/public/growth/growth-recommendation'
      preLoaderRoute: typeof ApiPublicGrowthGrowthRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/plan-nurture-test': {
      id: '/api/public/growth/plan-nurture-test'
      path: '/api/public/growth/plan-nurture-test'
      fullPath: '/api/public/growth/plan-nurture-test'
      preLoaderRoute: typeof ApiPublicGrowthPlanNurtureTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/register-nurture-reply-test': {
      id: '/api/public/growth/register-nurture-reply-test'
      path: '/api/public/growth/register-nurture-reply-test'
      fullPath: '/api/public/growth/register-nurture-reply-test'
      preLoaderRoute: typeof ApiPublicGrowthRegisterNurtureReplyTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/register-outcome': {
      id: '/api/public/growth/register-outcome'
      path: '/api/public/growth/register-outcome'
      fullPath: '/api/public/growth/register-outcome'
      preLoaderRoute: typeof ApiPublicGrowthRegisterOutcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/register-reviewed-nurture-reply': {
      id: '/api/public/growth/register-reviewed-nurture-reply'
      path: '/api/public/growth/register-reviewed-nurture-reply'
      fullPath: '/api/public/growth/register-reviewed-nurture-reply'
      preLoaderRoute: typeof ApiPublicGrowthRegisterReviewedNurtureReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/review-reconciliation': {
      id: '/api/public/growth/review-reconciliation'
      path: '/api/public/growth/review-reconciliation'
      fullPath: '/api/public/growth/review-reconciliation'
      preLoaderRoute: typeof ApiPublicGrowthReviewReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/route-lead': {
      id: '/api/public/growth/route-lead'
      path: '/api/public/growth/route-lead'
      fullPath: '/api/public/growth/route-lead'
      preLoaderRoute: typeof ApiPublicGrowthRouteLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCustomerIdRoute: typeof AuthenticatedAdminCustomerIdRoute
  AuthenticatedAdminAgentsRoute: typeof AuthenticatedAdminAgentsRoute
  AuthenticatedAdminAiAssistentRoute: typeof AuthenticatedAdminAiAssistentRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminGrowthRoute: typeof AuthenticatedAdminGrowthRoute
  AuthenticatedAdminKonversationerRoute: typeof AuthenticatedAdminKonversationerRoute
  AuthenticatedAdminProfilerRoute: typeof AuthenticatedAdminProfilerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCustomerIdRoute: AuthenticatedAdminCustomerIdRoute,
  AuthenticatedAdminAgentsRoute: AuthenticatedAdminAgentsRoute,
  AuthenticatedAdminAiAssistentRoute: AuthenticatedAdminAiAssistentRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminGrowthRoute: AuthenticatedAdminGrowthRoute,
  AuthenticatedAdminKonversationerRoute: AuthenticatedAdminKonversationerRoute,
  AuthenticatedAdminProfilerRoute: AuthenticatedAdminProfilerRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KontaktRoute: KontaktRoute,
  McpRoute: McpRoute,
  OmRoute: OmRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TakoffertRoute: TakoffertRoute,
  VillkorRoute: VillkorRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  LeadKontaktadRoute: LeadKontaktadRoute,
  OffertSlugRoute: OffertSlugRoute,
  TestTakoffertRoute: TestTakoffertRoute,
  TestOffertSlugRoute: TestOffertSlugRoute,
  ApiPublicAgentsAutonomousTickRoute: ApiPublicAgentsAutonomousTickRoute,
  ApiPublicAgentsDispatchTestRoute: ApiPublicAgentsDispatchTestRoute,
  ApiPublicAgentsImprovementReviewTestRoute:
    ApiPublicAgentsImprovementReviewTestRoute,
  ApiPublicAgentsProcessShadowBatchTestRoute:
    ApiPublicAgentsProcessShadowBatchTestRoute,
  ApiPublicAgentsProcessTestRoute: ApiPublicAgentsProcessTestRoute,
  ApiPublicAgentsShadowReviewTestRoute: ApiPublicAgentsShadowReviewTestRoute,
  ApiPublicGrowthAnalyzeLeadRoute: ApiPublicGrowthAnalyzeLeadRoute,
  ApiPublicGrowthAssignVariantRoute: ApiPublicGrowthAssignVariantRoute,
  ApiPublicGrowthClaimLeadReminderRoute: ApiPublicGrowthClaimLeadReminderRoute,
  ApiPublicGrowthClaimNurtureReviewRoute:
    ApiPublicGrowthClaimNurtureReviewRoute,
  ApiPublicGrowthCompleteLeadReminderRoute:
    ApiPublicGrowthCompleteLeadReminderRoute,
  ApiPublicGrowthCompleteNurtureReviewRoute:
    ApiPublicGrowthCompleteNurtureReviewRoute,
  ApiPublicGrowthCustomerConfigRoute: ApiPublicGrowthCustomerConfigRoute,
  ApiPublicGrowthDeliveryRecoveryRoute: ApiPublicGrowthDeliveryRecoveryRoute,
  ApiPublicGrowthDueLeadRemindersRoute: ApiPublicGrowthDueLeadRemindersRoute,
  ApiPublicGrowthDueNurtureReviewsRoute: ApiPublicGrowthDueNurtureReviewsRoute,
  ApiPublicGrowthFailLeadReminderRoute: ApiPublicGrowthFailLeadReminderRoute,
  ApiPublicGrowthFailNurtureReviewRoute: ApiPublicGrowthFailNurtureReviewRoute,
  ApiPublicGrowthGrowthRecommendationRoute:
    ApiPublicGrowthGrowthRecommendationRoute,
  ApiPublicGrowthPlanNurtureTestRoute: ApiPublicGrowthPlanNurtureTestRoute,
  ApiPublicGrowthRegisterNurtureReplyTestRoute:
    ApiPublicGrowthRegisterNurtureReplyTestRoute,
  ApiPublicGrowthRegisterOutcomeRoute: ApiPublicGrowthRegisterOutcomeRoute,
  ApiPublicGrowthRegisterReviewedNurtureReplyRoute:
    ApiPublicGrowthRegisterReviewedNurtureReplyRoute,
  ApiPublicGrowthReviewReconciliationRoute:
    ApiPublicGrowthReviewReconciliationRoute,
  ApiPublicGrowthRouteLeadRoute: ApiPublicGrowthRouteLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
