/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TakoffertRouteImport } from './routes/takoffert'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as OffertSlugRouteImport } from './routes/offert.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCustomerIdRouteImport } from './routes/_authenticated/admin/$customerId'
import { Route as AuthenticatedAdminAiAssistentRouteImport } from './routes/_authenticated/admin/ai-assistent'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin/crm'
import { Route as AuthenticatedAdminGrowthRouteImport } from './routes/_authenticated/admin/growth'
import { Route as AuthenticatedAdminKonversationerRouteImport } from './routes/_authenticated/admin/konversationer'
import { Route as AuthenticatedAdminProfilerRouteImport } from './routes/_authenticated/admin/profiler'
import { Route as ApiPublicGrowthAnalyzeLeadRouteImport } from './routes/api/public/growth/analyze-lead'
import { Route as ApiPublicGrowthAssignVariantRouteImport } from './routes/api/public/growth/assign-variant'
import { Route as ApiPublicGrowthGrowthRecommendationRouteImport } from './routes/api/public/growth/growth-recommendation'
import { Route as ApiPublicGrowthRegisterOutcomeRouteImport } from './routes/api/public/growth/register-outcome'
import { Route as ApiPublicGrowthRouteLeadRouteImport } from './routes/api/public/growth/route-lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TakoffertRoute = TakoffertRouteImport.update({
  id: '/takoffert',
  path: '/takoffert',
  getParentRoute: () => rootRouteImport,
} as any)
const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const OffertSlugRoute = OffertSlugRouteImport.update({
  id: '/offert/$slug',
  path: '/offert/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCustomerIdRoute =
  AuthenticatedAdminCustomerIdRouteImport.update({
    id: '/admin/$customerId',
    path: '/admin/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAiAssistentRoute =
  AuthenticatedAdminAiAssistentRouteImport.update({
    id: '/admin/ai-assistent',
    path: '/admin/ai-assistent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGrowthRoute =
  AuthenticatedAdminGrowthRouteImport.update({
    id: '/admin/growth',
    path: '/admin/growth',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKonversationerRoute =
  AuthenticatedAdminKonversationerRouteImport.update({
    id: '/admin/konversationer',
    path: '/admin/konversationer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProfilerRoute =
  AuthenticatedAdminProfilerRouteImport.update({
    id: '/admin/profiler',
    path: '/admin/profiler',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicGrowthAnalyzeLeadRoute =
  ApiPublicGrowthAnalyzeLeadRouteImport.update({
    id: '/api/public/growth/analyze-lead',
    path: '/api/public/growth/analyze-lead',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthAssignVariantRoute =
  ApiPublicGrowthAssignVariantRouteImport.update({
    id: '/api/public/growth/assign-variant',
    path: '/api/public/growth/assign-variant',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthGrowthRecommendationRoute =
  ApiPublicGrowthGrowthRecommendationRouteImport.update({
    id: '/api/public/growth/growth-recommendation',
    path: '/api/public/growth/growth-recommendation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthRegisterOutcomeRoute =
  ApiPublicGrowthRegisterOutcomeRouteImport.update({
    id: '/api/public/growth/register-outcome',
    path: '/api/public/growth/register-outcome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGrowthRouteLeadRoute =
  ApiPublicGrowthRouteLeadRouteImport.update({
    id: '/api/public/growth/route-lead',
    path: '/api/public/growth/route-lead',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takoffert': typeof TakoffertRoute
  '/villkor': typeof VillkorRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/offert/$slug': typeof OffertSlugRoute
  '/admin/$customerId': typeof AuthenticatedAdminCustomerIdRoute
  '/admin/ai-assistent': typeof AuthenticatedAdminAiAssistentRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/growth': typeof AuthenticatedAdminGrowthRoute
  '/admin/konversationer': typeof AuthenticatedAdminKonversationerRoute
  '/admin/profiler': typeof AuthenticatedAdminProfilerRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/growth/analyze-lead': typeof ApiPublicGrowthAnalyzeLeadRoute
  '/api/public/growth/assign-variant': typeof ApiPublicGrowthAssignVariantRoute
  '/api/public/growth/growth-recommendation': typeof ApiPublicGrowthGrowthRecommendationRoute
  '/api/public/growth/register-outcome': typeof ApiPublicGrowthRegisterOutcomeRoute
  '/api/public/growth/route-lead': typeof ApiPublicGrowthRouteLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takoffert': typeof TakoffertRoute
  '/villkor': typeof VillkorRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/offert/$slug': typeof OffertSlugRoute
  '/admin/$customerId': typeof AuthenticatedAdminCustomerIdRoute
  '/admin/ai-assistent': typeof AuthenticatedAdminAiAssistentRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/growth': typeof AuthenticatedAdminGrowthRoute
  '/admin/konversationer': typeof AuthenticatedAdminKonversationerRoute
  '/admin/profiler': typeof AuthenticatedAdminProfilerRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/growth/analyze-lead': typeof ApiPublicGrowthAnalyzeLeadRoute
  '/api/public/growth/assign-variant': typeof ApiPublicGrowthAssignVariantRoute
  '/api/public/growth/growth-recommendation': typeof ApiPublicGrowthGrowthRecommendationRoute
  '/api/public/growth/register-outcome': typeof ApiPublicGrowthRegisterOutcomeRoute
  '/api/public/growth/route-lead': typeof ApiPublicGrowthRouteLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takoffert': typeof TakoffertRoute
  '/villkor': typeof VillkorRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/offert/$slug': typeof OffertSlugRoute
  '/_authenticated/admin/$customerId': typeof AuthenticatedAdminCustomerIdRoute
  '/_authenticated/admin/ai-assistent': typeof AuthenticatedAdminAiAssistentRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/growth': typeof AuthenticatedAdminGrowthRoute
  '/_authenticated/admin/konversationer': typeof AuthenticatedAdminKonversationerRoute
  '/_authenticated/admin/profiler': typeof AuthenticatedAdminProfilerRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/growth/analyze-lead': typeof ApiPublicGrowthAnalyzeLeadRoute
  '/api/public/growth/assign-variant': typeof ApiPublicGrowthAssignVariantRoute
  '/api/public/growth/growth-recommendation': typeof ApiPublicGrowthGrowthRecommendationRoute
  '/api/public/growth/register-outcome': typeof ApiPublicGrowthRegisterOutcomeRoute
  '/api/public/growth/route-lead': typeof ApiPublicGrowthRouteLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cookies'
    | '/integritetspolicy'
    | '/mcp'
    | '/sitemap.xml'
    | '/takoffert'
    | '/villkor'
    | '/.well-known/oauth-protected-resource'
    | '/offert/$slug'
    | '/admin/$customerId'
    | '/admin/ai-assistent'
    | '/admin/crm'
    | '/admin/growth'
    | '/admin/konversationer'
    | '/admin/profiler'
    | '/admin/'
    | '/api/public/growth/analyze-lead'
    | '/api/public/growth/assign-variant'
    | '/api/public/growth/growth-recommendation'
    | '/api/public/growth/register-outcome'
    | '/api/public/growth/route-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cookies'
    | '/integritetspolicy'
    | '/mcp'
    | '/sitemap.xml'
    | '/takoffert'
    | '/villkor'
    | '/.well-known/oauth-protected-resource'
    | '/offert/$slug'
    | '/admin/$customerId'
    | '/admin/ai-assistent'
    | '/admin/crm'
    | '/admin/growth'
    | '/admin/konversationer'
    | '/admin/profiler'
    | '/admin'
    | '/api/public/growth/analyze-lead'
    | '/api/public/growth/assign-variant'
    | '/api/public/growth/growth-recommendation'
    | '/api/public/growth/register-outcome'
    | '/api/public/growth/route-lead'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cookies'
    | '/integritetspolicy'
    | '/mcp'
    | '/sitemap.xml'
    | '/takoffert'
    | '/villkor'
    | '/.well-known/oauth-protected-resource'
    | '/offert/$slug'
    | '/_authenticated/admin/$customerId'
    | '/_authenticated/admin/ai-assistent'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/growth'
    | '/_authenticated/admin/konversationer'
    | '/_authenticated/admin/profiler'
    | '/_authenticated/admin/'
    | '/api/public/growth/analyze-lead'
    | '/api/public/growth/assign-variant'
    | '/api/public/growth/growth-recommendation'
    | '/api/public/growth/register-outcome'
    | '/api/public/growth/route-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TakoffertRoute: typeof TakoffertRoute
  VillkorRoute: typeof VillkorRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  OffertSlugRoute: typeof OffertSlugRoute
  ApiPublicGrowthAnalyzeLeadRoute: typeof ApiPublicGrowthAnalyzeLeadRoute
  ApiPublicGrowthAssignVariantRoute: typeof ApiPublicGrowthAssignVariantRoute
  ApiPublicGrowthGrowthRecommendationRoute: typeof ApiPublicGrowthGrowthRecommendationRoute
  ApiPublicGrowthRegisterOutcomeRoute: typeof ApiPublicGrowthRegisterOutcomeRoute
  ApiPublicGrowthRouteLeadRoute: typeof ApiPublicGrowthRouteLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takoffert': {
      id: '/takoffert'
      path: '/takoffert'
      fullPath: '/takoffert'
      preLoaderRoute: typeof TakoffertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offert/$slug': {
      id: '/offert/$slug'
      path: '/offert/$slug'
      fullPath: '/offert/$slug'
      preLoaderRoute: typeof OffertSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$customerId': {
      id: '/_authenticated/admin/$customerId'
      path: '/admin/$customerId'
      fullPath: '/admin/$customerId'
      preLoaderRoute: typeof AuthenticatedAdminCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/ai-assistent': {
      id: '/_authenticated/admin/ai-assistent'
      path: '/admin/ai-assistent'
      fullPath: '/admin/ai-assistent'
      preLoaderRoute: typeof AuthenticatedAdminAiAssistentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/growth': {
      id: '/_authenticated/admin/growth'
      path: '/admin/growth'
      fullPath: '/admin/growth'
      preLoaderRoute: typeof AuthenticatedAdminGrowthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/konversationer': {
      id: '/_authenticated/admin/konversationer'
      path: '/admin/konversationer'
      fullPath: '/admin/konversationer'
      preLoaderRoute: typeof AuthenticatedAdminKonversationerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/profiler': {
      id: '/_authenticated/admin/profiler'
      path: '/admin/profiler'
      fullPath: '/admin/profiler'
      preLoaderRoute: typeof AuthenticatedAdminProfilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/growth/analyze-lead': {
      id: '/api/public/growth/analyze-lead'
      path: '/api/public/growth/analyze-lead'
      fullPath: '/api/public/growth/analyze-lead'
      preLoaderRoute: typeof ApiPublicGrowthAnalyzeLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/assign-variant': {
      id: '/api/public/growth/assign-variant'
      path: '/api/public/growth/assign-variant'
      fullPath: '/api/public/growth/assign-variant'
      preLoaderRoute: typeof ApiPublicGrowthAssignVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/growth-recommendation': {
      id: '/api/public/growth/growth-recommendation'
      path: '/api/public/growth/growth-recommendation'
      fullPath: '/api/public/growth/growth-recommendation'
      preLoaderRoute: typeof ApiPublicGrowthGrowthRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/register-outcome': {
      id: '/api/public/growth/register-outcome'
      path: '/api/public/growth/register-outcome'
      fullPath: '/api/public/growth/register-outcome'
      preLoaderRoute: typeof ApiPublicGrowthRegisterOutcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/growth/route-lead': {
      id: '/api/public/growth/route-lead'
      path: '/api/public/growth/route-lead'
      fullPath: '/api/public/growth/route-lead'
      preLoaderRoute: typeof ApiPublicGrowthRouteLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCustomerIdRoute: typeof AuthenticatedAdminCustomerIdRoute
  AuthenticatedAdminAiAssistentRoute: typeof AuthenticatedAdminAiAssistentRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminGrowthRoute: typeof AuthenticatedAdminGrowthRoute
  AuthenticatedAdminKonversationerRoute: typeof AuthenticatedAdminKonversationerRoute
  AuthenticatedAdminProfilerRoute: typeof AuthenticatedAdminProfilerRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCustomerIdRoute: AuthenticatedAdminCustomerIdRoute,
  AuthenticatedAdminAiAssistentRoute: AuthenticatedAdminAiAssistentRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminGrowthRoute: AuthenticatedAdminGrowthRoute,
  AuthenticatedAdminKonversationerRoute: AuthenticatedAdminKonversationerRoute,
  AuthenticatedAdminProfilerRoute: AuthenticatedAdminProfilerRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TakoffertRoute: TakoffertRoute,
  VillkorRoute: VillkorRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  OffertSlugRoute: OffertSlugRoute,
  ApiPublicGrowthAnalyzeLeadRoute: ApiPublicGrowthAnalyzeLeadRoute,
  ApiPublicGrowthAssignVariantRoute: ApiPublicGrowthAssignVariantRoute,
  ApiPublicGrowthGrowthRecommendationRoute:
    ApiPublicGrowthGrowthRecommendationRoute,
  ApiPublicGrowthRegisterOutcomeRoute: ApiPublicGrowthRegisterOutcomeRoute,
  ApiPublicGrowthRouteLeadRoute: ApiPublicGrowthRouteLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
